
version: '4'

services:
# Backend / PHP
  app:
    image: myphpapp
    build: .
    volumes:
      - ./:/usr/src/phpapp
      - ./storage:/usr/src/phpapp/storage
      - ./storage/app:/usr/src/phpapp/storage/app 
    #php -S localhost:9000 -t /usr/src/phpapp/public
    #supervisord -c /etc/supervisor/conf.d/laravel-worker.conf
    command: php -S localhost:9000 -t /usr/src/phpapp/public
    #command: ./supervisor.sh
    restart: always
    ports:
     - "9000:9000"
    network_mode: host

  supervisor:
    image: customsupervisor
    build: .
    command: ./supervisor.sh
    network_mode: host
    restart: always
    volumes:
      - ./:/usr/src/phpapp
      - ./laravel-worker:/etc/supervisor/conf.d
      - ./supervisor.sh:/usr/src/phpapp
# Redis
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis-conf/redis.conf:/etc/redis-conf/redis.conf
    network_mode: host   

